// <auto-generated />
using System;
using IceTrackPlatform.API.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IceTrackPlatform.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706143347_SplitRatingIntoThreeFields")]
    partial class SplitRatingIntoThreeFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IceTrackPlatform.API.Assets_Management.Domain.Model.Aggregates.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("CantEquipment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("cant_equipment");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_name");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("p_k_sites");

                    b.ToTable("sites");
                });

            modelBuilder.Entity("IceTrackPlatform.API.Dashboard.Domain.Model.Aggregates.DashboardConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DefaultSiteId")
                        .HasColumnType("integer")
                        .HasColumnName("default_site_id");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_dashboard_configs");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_dashboard_configs_user_id");

                    b.ToTable("dashboard_configs");
                });

            modelBuilder.Entity("IceTrackPlatform.API.Dashboard.Domain.Model.Entities.DashboardCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("card_type");

                    b.Property<int>("DashboardConfigId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id")
                        .HasName("p_k_dashboard_cards");

                    b.HasIndex("DashboardConfigId")
                        .HasDatabaseName("i_x_dashboard_cards__dashboard_config_id");

                    b.ToTable("dashboard_cards");
                });

            modelBuilder.Entity("IceTrackPlatform.API.Feedback.Domain.Model.Aggregates.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("service_request_id");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("integer")
                        .HasColumnName("technician_id");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_reviews");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("IceTrackPlatform.API.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("IceTrackPlatform.API.Monitoring.Domain.Model.Aggregates.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean")
                        .HasColumnName("online");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<int?>("ReminderIntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("reminder_interval_days");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serial");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("p_k_equipment");

                    b.ToTable("equipment");
                });

            modelBuilder.Entity("IceTrackPlatform.API.Notifications.Domain.Model.Aggregates.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismissed_at");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_id");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("IceTrackPlatform.API.ServiceRequests.Domain.Model.Aggregates.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("PhotoUrls")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_urls");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_interventions");

                    b.ToTable("interventions");
                });

            modelBuilder.Entity("IceTrackPlatform.API.ServiceRequests.Domain.Model.Aggregates.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canceled_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_service_requests");

                    b.ToTable("service_requests");
                });

            modelBuilder.Entity("IceTrackPlatform.API.Technicians.Domain.Model.Aggregates.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialty");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_technicians");

                    b.ToTable("technicians");
                });

            modelBuilder.Entity("IceTrackPlatform.API.Dashboard.Domain.Model.Aggregates.DashboardConfig", b =>
                {
                    b.OwnsOne("IceTrackPlatform.API.Dashboard.Domain.Model.ValueObjects.TemperatureRange", "DefaultTemperatureRange", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("default_temperature_range_label");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("default_temperature_range_value");

                            b1.HasKey("Id")
                                .HasName("p_k_dashboard_configs");

                            b1.ToTable("dashboard_configs");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_dashboard_configs_dashboard_configs__id");
                        });

                    b.Navigation("DefaultTemperatureRange")
                        .IsRequired();
                });

            modelBuilder.Entity("IceTrackPlatform.API.Dashboard.Domain.Model.Entities.DashboardCard", b =>
                {
                    b.HasOne("IceTrackPlatform.API.Dashboard.Domain.Model.Aggregates.DashboardConfig", null)
                        .WithMany("Cards")
                        .HasForeignKey("DashboardConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_dashboard_cards_dashboard_configs__dashboard_config_id");
                });

            modelBuilder.Entity("IceTrackPlatform.API.Feedback.Domain.Model.Aggregates.Review", b =>
                {
                    b.OwnsOne("IceTrackPlatform.API.Feedback.Domain.Model.ValueObjects.ReviewRating", "Rating", b1 =>
                        {
                            b1.Property<int>("ReviewId")
                                .HasColumnType("integer");

                            b1.Property<int>("Comunicacion")
                                .HasColumnType("integer")
                                .HasColumnName("comunicacion");

                            b1.Property<int>("Eficiencia")
                                .HasColumnType("integer")
                                .HasColumnName("eficiencia");

                            b1.Property<int>("Profesionalidad")
                                .HasColumnType("integer")
                                .HasColumnName("profesionalidad");

                            b1.HasKey("ReviewId")
                                .HasName("p_k_reviews");

                            b1.ToTable("reviews");

                            b1.WithOwner()
                                .HasForeignKey("ReviewId")
                                .HasConstraintName("f_k_reviews_reviews__review_id");
                        });

                    b.Navigation("Rating")
                        .IsRequired();
                });

            modelBuilder.Entity("IceTrackPlatform.API.ServiceRequests.Domain.Model.Aggregates.Intervention", b =>
                {
                    b.OwnsOne("IceTrackPlatform.API.ServiceRequests.Domain.Model.ValueObjects.TechnicianId", "TechnicianId", b1 =>
                        {
                            b1.Property<int>("InterventionId")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("technician_id");

                            b1.HasKey("InterventionId")
                                .HasName("p_k_interventions");

                            b1.ToTable("interventions");

                            b1.WithOwner()
                                .HasForeignKey("InterventionId")
                                .HasConstraintName("f_k_interventions_interventions__intervention_id");
                        });

                    b.OwnsOne("IceTrackPlatform.API.ServiceRequests.Domain.Model.ValueObjects.InterventionStatus", "Status", b1 =>
                        {
                            b1.Property<int>("InterventionId")
                                .HasColumnType("integer");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status");

                            b1.HasKey("InterventionId")
                                .HasName("p_k_interventions");

                            b1.ToTable("interventions");

                            b1.WithOwner()
                                .HasForeignKey("InterventionId")
                                .HasConstraintName("f_k_interventions_interventions__intervention_id");
                        });

                    b.OwnsOne("IceTrackPlatform.API.ServiceRequests.Domain.Model.ValueObjects.ServiceRequestId", "ServiceRequestId", b1 =>
                        {
                            b1.Property<int>("InterventionId")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("service_request_id");

                            b1.HasKey("InterventionId")
                                .HasName("p_k_interventions");

                            b1.ToTable("interventions");

                            b1.WithOwner()
                                .HasForeignKey("InterventionId")
                                .HasConstraintName("f_k_interventions_interventions__intervention_id");
                        });

                    b.Navigation("ServiceRequestId")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();

                    b.Navigation("TechnicianId")
                        .IsRequired();
                });

            modelBuilder.Entity("IceTrackPlatform.API.ServiceRequests.Domain.Model.Aggregates.ServiceRequest", b =>
                {
                    b.OwnsOne("IceTrackPlatform.API.ServiceRequests.Domain.Model.ValueObjects.TechnicianId", "TechnicianId", b1 =>
                        {
                            b1.Property<int>("ServiceRequestId")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("technician_id");

                            b1.HasKey("ServiceRequestId")
                                .HasName("p_k_service_requests");

                            b1.ToTable("service_requests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId")
                                .HasConstraintName("f_k_service_requests_service_requests__service_request_id");
                        });

                    b.OwnsOne("IceTrackPlatform.API.ServiceRequests.Domain.Model.ValueObjects.AssignedTo", "AssignedTo", b1 =>
                        {
                            b1.Property<int>("ServiceRequestId")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("assigned_to");

                            b1.HasKey("ServiceRequestId")
                                .HasName("p_k_service_requests");

                            b1.ToTable("service_requests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId")
                                .HasConstraintName("f_k_service_requests_service_requests__service_request_id");
                        });

                    b.OwnsOne("IceTrackPlatform.API.ServiceRequests.Domain.Model.ValueObjects.EquipmentId", "EquipmentId", b1 =>
                        {
                            b1.Property<int>("ServiceRequestId")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("equipment_id");

                            b1.HasKey("ServiceRequestId")
                                .HasName("p_k_service_requests");

                            b1.ToTable("service_requests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId")
                                .HasConstraintName("f_k_service_requests_service_requests__service_request_id");
                        });

                    b.OwnsOne("IceTrackPlatform.API.ServiceRequests.Domain.Model.ValueObjects.RequesterId", "RequesterId", b1 =>
                        {
                            b1.Property<int>("ServiceRequestId")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("requester_id");

                            b1.HasKey("ServiceRequestId")
                                .HasName("p_k_service_requests");

                            b1.ToTable("service_requests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId")
                                .HasConstraintName("f_k_service_requests_service_requests__service_request_id");
                        });

                    b.OwnsOne("IceTrackPlatform.API.ServiceRequests.Domain.Model.ValueObjects.ServiceRequestPriority", "Priority", b1 =>
                        {
                            b1.Property<int>("ServiceRequestId")
                                .HasColumnType("integer");

                            b1.Property<string>("Priority")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("priority");

                            b1.HasKey("ServiceRequestId")
                                .HasName("p_k_service_requests");

                            b1.ToTable("service_requests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId")
                                .HasConstraintName("f_k_service_requests_service_requests__service_request_id");
                        });

                    b.OwnsOne("IceTrackPlatform.API.ServiceRequests.Domain.Model.ValueObjects.ServiceRequestStatus", "Status", b1 =>
                        {
                            b1.Property<int>("ServiceRequestId")
                                .HasColumnType("integer");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status");

                            b1.HasKey("ServiceRequestId")
                                .HasName("p_k_service_requests");

                            b1.ToTable("service_requests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId")
                                .HasConstraintName("f_k_service_requests_service_requests__service_request_id");
                        });

                    b.OwnsOne("IceTrackPlatform.API.ServiceRequests.Domain.Model.ValueObjects.ServiceRequestType", "Type", b1 =>
                        {
                            b1.Property<int>("ServiceRequestId")
                                .HasColumnType("integer");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("type");

                            b1.HasKey("ServiceRequestId")
                                .HasName("p_k_service_requests");

                            b1.ToTable("service_requests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId")
                                .HasConstraintName("f_k_service_requests_service_requests__service_request_id");
                        });

                    b.OwnsOne("IceTrackPlatform.API.ServiceRequests.Domain.Model.ValueObjects.SiteId", "SiteId", b1 =>
                        {
                            b1.Property<int>("ServiceRequestId")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("site_id");

                            b1.HasKey("ServiceRequestId")
                                .HasName("p_k_service_requests");

                            b1.ToTable("service_requests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId")
                                .HasConstraintName("f_k_service_requests_service_requests__service_request_id");
                        });

                    b.Navigation("AssignedTo")
                        .IsRequired();

                    b.Navigation("EquipmentId")
                        .IsRequired();

                    b.Navigation("Priority")
                        .IsRequired();

                    b.Navigation("RequesterId")
                        .IsRequired();

                    b.Navigation("SiteId")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();

                    b.Navigation("TechnicianId");

                    b.Navigation("Type")
                        .IsRequired();
                });

            modelBuilder.Entity("IceTrackPlatform.API.Technicians.Domain.Model.Aggregates.Technician", b =>
                {
                    b.OwnsOne("IceTrackPlatform.API.Technicians.Domain.Model.ValueObjects.ProviderId", "ProviderId", b1 =>
                        {
                            b1.Property<int>("TechnicianId")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("provider_id");

                            b1.HasKey("TechnicianId")
                                .HasName("p_k_technicians");

                            b1.ToTable("technicians");

                            b1.WithOwner()
                                .HasForeignKey("TechnicianId")
                                .HasConstraintName("f_k_technicians_technicians__technician_id");
                        });

                    b.Navigation("ProviderId")
                        .IsRequired();
                });

            modelBuilder.Entity("IceTrackPlatform.API.Dashboard.Domain.Model.Aggregates.DashboardConfig", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
